export const editorOptions = {
  automaticLayout: true,
  insertSpaces: true,
  tabSize: 2,
  matchBrackets: 'always',
  dragAndDrop: true,
  quickSuggestions: {
    other: true,
    comments: true,
    strings: true,
  },
  'semanticHighlighting.enabled': true,
  suggest: {
    showMethods: true,
    showFunctions: true,
    showConstructors: true,
    showFields: true,
    showVariables: true,
    showClasses: true,
    showStructs: true,
    showInterfaces: true,
    showModules: true,
    showProperties: true,
    showEvents: true,
    showOperators: true,
    showUnits: true,
    showValues: true,
    showConstants: true,
    showEnums: true,
    showEnumMembers: true,
    showKeywords: true,
    showWords: true,
    showColors: true,
    showFiles: true,
    showReferences: true,
    showFolders: true,
    showTypeParameters: true,
    showIssues: true,
    showUsers: true,
    showSnippets: true,
  },
  suggestOnTriggerCharacters: true,
  parameterHints: {
    cycle: true,
    enabled: true,
  },
  scrollBeyondLastLine: false,
  snippetSuggestions: 'inline',
  statusBar: {
    visible: true,
  },
};
